feat handlers completed
MadeOfSt0ne/go-rest-api-homework pull request #1
Opened 2023-12-05 18:17 UTC by MadeOfSt0ne

Add handlers: getTasks, getTaskById, postTask, deleteTask.

2023-12-11 15:20 UTC, just-musha requested changes
Привет! Отличная работа, круто что завел константы. Оставила коментарий с предложением явно обработать ошибку. В примерах курса этого не было, но это хорошая практика в реальной работе

2023-12-11 15:20 UTC, just-musha commented on precode.go
> +// Сделал константы чтобы избежать возможных ошибок. Или так не принято делать?)
Да можно, константы для повторяющихся значений - это хорошо

2023-12-11 15:20 UTC, just-musha commented on precode.go
> +	w.Write(resp)
В примерах в курсе это не показано, но на самом деле Write возвращает 2 значения

`Write([]byte) (int, error)` - https://golang.cafe/blog/golang-writer-example.html

Обычно в таком случае принято явно проверять ошибку на nil, и что-то с ней сделать - либо залогировать (например можно сейчас через fmt.Printf) или явно заигнорировать при помощи `_`. 
Давай что-то из этого сделаем здесь и ниже по коду, где есть Write

2023-12-14 14:37 UTC, MadeOfSt0ne commented on precode.go
> +	w.Write(resp)
Добавил проверку на ошибки

2023-12-14 15:57 UTC, just-musha approved these changes
Спасибо! Комент не критичный, так что принято.

2023-12-14 15:57 UTC, just-musha commented on precode.go
> +		fmt.Printf("Ошибка при записи ответа.\n")
Сам err тоже неплохо бы вывести

2023-12-14 17:39 UTC, MadeOfSt0ne commented on precode.go
> +		fmt.Printf("Ошибка при записи ответа.\n")
сделано

2024-03-29 14:06 UTC, merged